In [17]:
import pandas as pd

print(pd.__version__)

2.1.0


In [18]:
import numpy as np

In [19]:
df = pd.read_csv('housing.csv')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [21]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [22]:
missing_data = df.isna()  # or df.isnull()

columns_with_missing_data = missing_data.any()

print(columns_with_missing_data)

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool


In [23]:
df['ocean_proximity']

0        NEAR BAY
1        NEAR BAY
2        NEAR BAY
3        NEAR BAY
4        NEAR BAY
           ...   
20635      INLAND
20636      INLAND
20637      INLAND
20638      INLAND
20639      INLAND
Name: ocean_proximity, Length: 20640, dtype: object

In [24]:
unique_values_count = df['ocean_proximity'].nunique()
print("Number of unique values:", unique_values_count)

Number of unique values: 5


In [25]:
condition = df['ocean_proximity'] == 'NEAR BAY'

near_bay_df = df[condition]

# we do not need ocean_proximity here, because it is all NEAR BAY
del near_bay_df['ocean_proximity']

near_bay_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0  
4       565.0       259.0         3.8462            342200.0

In [26]:
near_bay_df['median_house_value']

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
19067    297600.0
19068    208000.0
19069    262300.0
19077    213200.0
19104    246300.0
Name: median_house_value, Length: 2290, dtype: float64

In [27]:
average_value = near_bay_df['median_house_value'].mean()
average_value

259212.31179039303


    Calculate the average of total_bedrooms column in the dataset.
    Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
    Now, calculate the average of total_bedrooms again.
    Has it changed?

In [28]:
df1 = df.copy()

bedrooms_avarage = df1['total_bedrooms'].mean()
bedrooms_avarage

537.8705525375618

In [29]:
df1['total_bedrooms'].fillna(bedrooms_avarage, inplace=True)

In [30]:
new_bedrooms_avarage = df1['total_bedrooms'].mean()
new_bedrooms_avarage

537.8705525375617

Considering change as 3 digits after the decimal point, it has not changed


1.    Select all the options located on islands.
2.    Select only columns housing_median_age, total_rooms, total_bedrooms.
3.    Get the underlying NumPy array. Let's call it X.
4.    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5.    Compute the inverse of XTX.
6.    Create an array y with values [950, 1300, 800, 1000, 1300].
7.    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8.    What's the value of the last element of w?


In [32]:
df1 = df.copy()

In [33]:
condition = df['ocean_proximity'] == 'ISLAND'

island_df = df[condition]

# we do not need ocean_proximity here, because it is all NEAR BAY
del island_df['ocean_proximity']

island_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  
8314       744.0       331.0         2.1579            450000.0  
8315      1100.0       431.0         2.8333            414700.0  
8316       733.0       288.0         3.3906            300000.0  
8317       341.0       160.0         2.7361            450000.0  
8318       422.0       173.0         2.6042            287500.0

In [34]:
island_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 8314 to 8318
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           5 non-null      float64
 1   latitude            5 non-null      float64
 2   housing_median_age  5 non-null      float64
 3   total_rooms         5 non-null      float64
 4   total_bedrooms      5 non-null      float64
 5   population          5 non-null      float64
 6   households          5 non-null      float64
 7   median_income       5 non-null      float64
 8   median_house_value  5 non-null      float64
dtypes: float64(9)
memory usage: 400.0 bytes


In [35]:
new_df = island_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
new_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [36]:
X = island_df[['housing_median_age', 'total_rooms', 'total_bedrooms']].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [37]:
X.T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [42]:
XTX = X.T @ X 
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [43]:
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [44]:
y = [950, 1300, 800, 1000, 1300]

In [48]:
w = inverse_XTX @ X.T @ y

In [49]:
w[-1]

5.699229455065586